<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kate McCarthy">

<title>Lab 1: Data Science Tools</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lab-01_files/libs/clipboard/clipboard.min.js"></script>
<script src="lab-01_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="lab-01_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="lab-01_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="lab-01_files/libs/quarto-html/popper.min.js"></script>
<script src="lab-01_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lab-01_files/libs/quarto-html/anchor.min.js"></script>
<link href="lab-01_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lab-01_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lab-01_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lab-01_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lab-01_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="lab-01_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="lab-01_files/libs/tabwid-1.1.3/tabwid.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#libraries" id="toc-libraries" class="nav-link active" data-scroll-target="#libraries">Libraries</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#q1" id="toc-q1" class="nav-link" data-scroll-target="#q1"><strong>Question 1</strong>: Daily Conditions Report</a></li>
  <li><a href="#q2" id="toc-q2" class="nav-link" data-scroll-target="#q2"><strong>Question 2</strong>: Basin Metadata Join</a>
  <ul class="collapse">
  <li><a href="#the-anatomy-of-a-join" id="toc-the-anatomy-of-a-join" class="nav-link" data-scroll-target="#the-anatomy-of-a-join">The anatomy of a join</a></li>
  <li><a href="#graduate-expectations" id="toc-graduate-expectations" class="nav-link" data-scroll-target="#graduate-expectations">Graduate expectations</a></li>
  </ul></li>
  <li><a href="#q3" id="toc-q3" class="nav-link" data-scroll-target="#q3"><strong>Question 3</strong>: Per-Unit-Area Normalization</a></li>
  <li><a href="#q4" id="toc-q4" class="nav-link" data-scroll-target="#q4"><strong>Question 4</strong>: Low-Flow Threshold Monitoring</a></li>
  <li><a href="#q5" id="toc-q5" class="nav-link" data-scroll-target="#q5"><strong>Question 5</strong>: Annual Water Year Summary</a></li>
  <li><a href="#q6" id="toc-q6" class="nav-link" data-scroll-target="#q6"><strong>Question 6</strong>: Basin-Wide Trend Analysis</a></li>
  <li><a href="#q7" id="toc-q7" class="nav-link" data-scroll-target="#q7"><strong>Question 7</strong>: The Moving Center of Drought</a></li>
  <li><a href="#q8" id="toc-q8" class="nav-link" data-scroll-target="#q8"><strong>Question 8</strong>: Seasonal Regimes and Peak Timing</a></li>
  <li><a href="#q9" id="toc-q9" class="nav-link" data-scroll-target="#q9"><strong>Question 9</strong>: Predicting Lees Ferry from Upstream Conditions</a>
  <ul class="collapse">
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data Preparation</a></li>
  <li><a href="#model-building" id="toc-model-building" class="nav-link" data-scroll-target="#model-building">Model Building</a></li>
  </ul></li>
  <li><a href="#q10" id="toc-q10" class="nav-link" data-scroll-target="#q10"><strong>Question 10</strong>: Model Evaluation</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#going-further-ungraded" id="toc-going-further-ungraded" class="nav-link" data-scroll-target="#going-further-ungraded">Going Further (ungraded)</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 1: Data Science Tools</h1>
<p class="subtitle lead">Exploring Streamflow Across the Colorado River Basin</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kate McCarthy <a href="mailto:katherine.mccarthy@colostate.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/colorado-river.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>In January 2023, the federal government announced the first-ever Tier 3 shortage on the Colorado River — triggering mandatory cuts to Arizona, Nevada, and Mexico. Those cuts were calculated from streamflow records like the ones you are about to pull.</p>
<p>The Colorado River Basin supplies drinking water to 40 million people across 7 US states, irrigates 5 million acres of farmland, and is governed by one of the oldest and most contested water rights agreements in American history — the Colorado River Compact of 1922. Understanding how streamflow varies across this system is not an academic exercise. It is the daily work of water managers, federal agencies, tribal water rights holders, and scientists navigating a river under compounding stress from drought, overallocation, and climate change.</p>
<p>In this lab you will work with real streamflow records pulled directly from the <strong>USGS National Water Information System (NWIS)</strong> — the same federal system water managers query every morning. You will build a complete analytical pipeline: from raw API call to normalized comparisons, threshold detection, basin-wide trend visualization, and a predictive model of the Compact’s key accounting point.</p>
<section id="libraries" class="level2">
<h2 class="anchored" data-anchor-id="libraries">Libraries</h2>
<p>Install and load the following packages. If any are missing, run <code>install.packages("packagename")</code> first:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>pacman::p_load()</code> installs any missing packages and loads them in one step — convenient for students setting up dependencies.</p>
</div>
</div>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>We will use the <code>dataRetrieval</code> package — developed and maintained by the USGS — to pull 44 years of daily mean discharge from 7 long-record gauges spanning the Colorado River’s main stem and major tributaries.</p>
<p>The USGS parameter code for discharge is <code>00060</code> (cubic feet per second). The statistic code <code>00003</code> is the daily mean value. Under the hood, <code>dataRetrieval</code> constructs and queries the same REST API URL we explored in lecture:</p>
<pre><code>https://waterservices.usgs.gov/nwis/dv/?sites=09380000&amp;parameterCd=00060&amp;statCd=00003</code></pre>
<p>The data can be grabbed below!</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>gauges <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>site_no,     <span class="sc">~</span>name,                           <span class="sc">~</span>state,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"09380000"</span>,   <span class="st">"Colorado R at Lees Ferry"</span>,      <span class="st">"AZ"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"09163500"</span>,   <span class="st">"Colorado R near CO-UT border"</span>,  <span class="st">"CO"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"09085000"</span>,   <span class="st">"Colorado R at Glenwood Springs"</span>,<span class="st">"CO"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"09306500"</span>,   <span class="st">"White R near Watson"</span>,           <span class="st">"UT"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"09379500"</span>,   <span class="st">"San Juan R near Bluff"</span>,         <span class="st">"UT"</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"09402500"</span>,   <span class="st">"Little Colorado R near Cameron"</span>,<span class="st">"AZ"</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"09421500"</span>,   <span class="st">"Colorado R below Hoover Dam"</span>,   <span class="st">"NV"</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>raw <span class="ot">&lt;-</span> <span class="fu">readNWISdv</span>(</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">siteNumbers =</span> gauges<span class="sc">$</span>site_no,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">parameterCd =</span> <span class="st">"00060"</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">startDate   =</span> <span class="st">"1980-01-01"</span>,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">endDate     =</span> <span class="st">"2023-12-31"</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">renameNWISColumns</span>() <span class="sc">|&gt;</span>              <span class="co"># renames X_00060_00003 → Flow</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(gauges, <span class="at">by =</span> <span class="st">"site_no"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(site_no, name, state, Date, Flow)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 109,667
Columns: 5
$ site_no &lt;chr&gt; "09085000", "09085000", "09085000", "09085000", "09085000", "0…
$ name    &lt;chr&gt; "Colorado R at Glenwood Springs", "Colorado R at Glenwood Spri…
$ state   &lt;chr&gt; "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "C…
$ Date    &lt;date&gt; 1980-01-01, 1980-01-02, 1980-01-03, 1980-01-04, 1980-01-05, 1…
$ Flow    &lt;dbl&gt; 620, 605, 582, 582, 575, 590, 582, 582, 582, 590, 560, 598, 59…</code></pre>
</div>
</div>
<p>Note: this chunk is cached (<code>cache = TRUE</code>). If you change the data-pull arguments and need fresh data, set <code>cache = FALSE</code> temporarily or delete the <code>_cache/</code> directory and re-render to force a new download.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>What does <code>glimpse()</code> tell you?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Before doing anything with a new dataset, always check: Does the row count make sense? Are data types correct (<code>Date</code> should be <code>&lt;date&gt;</code>, <code>Flow</code> should be <code>&lt;dbl&gt;</code>)? Are there obvious NAs or impossible values? For ~7 gauges × 44 years × 365 days you should expect roughly 112,000 rows.</p>
</div>
</div>
<hr>
</section>
<section id="q1" class="level1">
<h1><strong>Question 1</strong>: Daily Conditions Report</h1>
<p>You are a water resources analyst. Each morning you deliver a reproducible snapshot of current conditions to Colorado River Compact stakeholders. The analysis must be re-runnable on any date with a single change — that requires building it around <strong>parameter objects</strong> rather than hardcoded values.</p>
<p><strong>a.</strong> Create a <code>my.date</code> parameter object set to the last day of water year 2023 (September 30, 2023). Ensure it is stored as a proper <code>Date</code> object, not a character string.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>as.Date()</code> converts a character string to a Date. R stores dates internally as days since 1970-01-01, enabling date arithmetic (<code>my.date - 7</code> = one week earlier) and use in <code>filter()</code> comparisons. Hint: use <code>as.Date()</code> to convert strings to <code>Date</code> objects and confirm with <code>class()</code> before using date arithmetic or <code>filter()</code>.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>my.date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2023-09-30"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(my.date)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Date"</code></pre>
</div>
</div>
<p><strong>b.</strong> Compute the <strong>day-over-day change in discharge</strong> for each gauge — how much flow rose or fell compared to the previous day. Store this as a new column called <code>flow_delta</code>. This tells you whether conditions are improving or deteriorating, which is often more actionable than the raw level alone.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>raw_delta <span class="ot">&lt;-</span> raw <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Date, name) <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span> <span class="co">#group by gauge to get the delta at each site for each day</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">flow_delta =</span> Flow <span class="sc">-</span> <span class="fu">lag</span>(Flow)) <span class="sc">%&gt;%</span> </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(raw) <span class="sc">==</span> <span class="fu">nrow</span>(raw_delta) <span class="co">#check to make sure same number of rows </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p><strong>c.</strong> Filter to <code>my.date</code> and produce <strong>two formatted tables</strong> using <code>flextable</code>:</p>
<ul>
<li><strong>Table 1</strong>: The 5 gauges with the <strong>highest discharge</strong> — where is flow greatest right now?</li>
<li><strong>Table 2</strong>: The 5 gauges with the <strong>greatest day-over-day increase</strong> — where is flow rising fastest?</li>
</ul>
<p>Both tables should have clear column names, rounded numbers, and descriptive captions using <code>flextable</code> (see tip).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Introducing <code>flextable</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>flextable</code> creates publication-quality HTML tables directly from data frames.</p>
<p>Hint: use <code>flextable()</code> with <code>set_header_labels()</code>, <code>set_caption()</code>, and <code>autofit()</code> for clean tables. Use <code>slice_max()</code> to select top <code>n</code> rows and <code>round()</code> to tidy numeric columns before rendering.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>raw_delta_mydate <span class="ot">&lt;-</span> raw_delta <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Date <span class="sc">==</span> my.date)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">#table 1</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="do">##select data for table</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>highest_discharge_mydate <span class="ot">&lt;-</span> raw_delta_mydate <span class="sc">%&gt;%</span> </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(Flow, <span class="at">n =</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="sc">!</span>Flow) <span class="sc">%&gt;%</span> </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">!</span><span class="fu">c</span>(site_no, Date, flow_delta)) </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="do">##create table </span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>highest_discharge <span class="ot">&lt;-</span> <span class="fu">flextable</span>(highest_discharge_mydate) <span class="sc">%&gt;%</span> </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_header_labels</span>(<span class="at">Flow =</span> <span class="st">"Discharge (cfs)"</span>, <span class="at">state =</span> <span class="st">"State"</span>, <span class="at">name =</span> <span class="st">"Site Name"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_caption</span>(<span class="at">caption =</span> <span class="st">"Top 5 Colorado River Gauges with the Highest Discharge on September 30th, 2023."</span>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(highest_discharge)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>a flextable object.
col_keys: `name`, `state`, `Flow` 
header has 1 row(s) 
body has 5 row(s) 
original dataset sample: 
'data.frame':   5 obs. of  3 variables:
 $ name : chr  "Colorado R below Hoover Dam" "Little Colorado R near Cameron" "Colorado R at Lees Ferry" "Colorado R near CO-UT border" ...
 $ state: chr  "NV" "AZ" "AZ" "CO" ...
 $ Flow : num  7860 6950 6570 3470 680</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#table 2</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="do">##select data for table</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>highest_increase_mydate <span class="ot">&lt;-</span> raw_delta_mydate <span class="sc">%&gt;%</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(flow_delta, <span class="at">n =</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="sc">!</span>flow_delta) <span class="sc">%&gt;%</span> </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">!</span><span class="fu">c</span>(site_no, Date, Flow))</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="do">##create table </span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>highest_increase <span class="ot">&lt;-</span> <span class="fu">flextable</span>(highest_increase_mydate) <span class="sc">%&gt;%</span> </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_header_labels</span>(<span class="at">flow_delta =</span> <span class="st">"Change in Flow (cfs)"</span>, <span class="at">state =</span> <span class="st">"State"</span>, <span class="at">name =</span> <span class="st">"Site Name"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_caption</span>(<span class="at">caption =</span> <span class="st">"Top 5 Colorado River Gauges with the Highest Increase in Flow on September 30th, 2023."</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(highest_increase)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>a flextable object.
col_keys: `name`, `state`, `flow_delta` 
header has 1 row(s) 
body has 5 row(s) 
original dataset sample: 
'data.frame':   5 obs. of  3 variables:
 $ name      : chr  "Colorado R at Glenwood Springs" "White R near Watson" "Colorado R at Lees Ferry" "Little Colorado R near Cameron" ...
 $ state     : chr  "CO" "UT" "AZ" "AZ" ...
 $ flow_delta: num  8 -7 -10 -20 -50</code></pre>
</div>
</div>
<hr>
</section>
<section id="q2" class="level1">
<h1><strong>Question 2</strong>: Basin Metadata Join</h1>
<p>Raw discharge numbers alone don’t tell the full story. Lees Ferry always carries more water than the San Juan at Bluff — but that is largely because it drains over <strong>111,000 square miles</strong> versus the San Juan’s ~23,000. To compare these sites meaningfully, we need each gauge’s drainage area. That information lives in a separate table and must be <strong>joined in</strong>.</p>
<p>This is the core relational data problem: observations in one table, attributes in another, connected through a shared key. It is also one of the most error-prone operations in data science — not because the syntax is hard, but because bad joins fail silently.</p>
<section id="the-anatomy-of-a-join" class="level2">
<h2 class="anchored" data-anchor-id="the-anatomy-of-a-join">The anatomy of a join</h2>
<p>Before writing a single <code>_join()</code> call, answer three questions:</p>
<ol type="1">
<li><strong>What is the key?</strong> Which column(s) connect the two tables?</li>
<li><strong>What is the relationship?</strong> One-to-one, or one-to-many?</li>
<li><strong>What happens to non-matching rows?</strong> Keep them (with NAs), or drop them?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>The (main) four joins — and when to use each
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Keeps rows from…</th>
<th>Non-matching rows</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>left_join(x, y)</code></td>
<td>All of <code>x</code></td>
<td><code>y</code> columns filled with <code>NA</code></td>
</tr>
<tr class="even">
<td><code>right_join(x, y)</code></td>
<td>All of <code>y</code></td>
<td><code>x</code> columns filled with <code>NA</code></td>
</tr>
<tr class="odd">
<td><code>inner_join(x, y)</code></td>
<td>Only rows matching in <strong>both</strong></td>
<td>Dropped entirely</td>
</tr>
<tr class="even">
<td><code>full_join(x, y)</code></td>
<td>Both <code>x</code> and <code>y</code></td>
<td>NAs on whichever side has no match</td>
</tr>
</tbody>
</table>
<p><strong>The most common mistake</strong>: using <code>inner_join</code> when you meant <code>left_join</code>. An inner join silently drops every row from <code>x</code> that has no match in <code>y</code> — your dataset shrinks and you may not notice until downstream results are wrong.</p>
<p><strong>The second most common mistake</strong>: joining on a key that is not unique in one of the tables. If <code>site_no</code> appears twice in <code>site_meta</code>, every matching row in your flow data will be <strong>duplicated</strong> — your dataset grows and you may not notice.</p>
<p>Both failures are invisible without explicit verification. For graduate-level work, in your write-up briefly justify the join type you chose, quantify any unmatched keys or duplicates you observed, and discuss possible data provenance reasons for mismatches.</p>
</div>
</div>
<p><strong>a.</strong> Pull site metadata for all 7 gauges. Before joining, verify that <code>site_no</code> is actually unique in <code>site_meta</code> — a duplicated key will silently inflate your row count.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>site_meta <span class="ot">&lt;-</span> <span class="fu">readNWISsite</span>(gauges<span class="sc">$</span>site_no) <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    site_no,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    drain_area_va,   <span class="co"># drainage area in square miles</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    huc_cd,          <span class="co"># 8-digit HUC watershed code</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    dec_lat_va,      <span class="co"># latitude</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    dec_long_va      <span class="co"># longitude</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Is site_no actually unique? If any row shows n &gt; 1, the join will duplicate rows</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>site_meta <span class="sc">|&gt;</span> <span class="fu">count</span>(site_no) <span class="sc">|&gt;</span> <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] site_no n      
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Keys: primary and foreign
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>primary key</strong> uniquely identifies each row in its own table. <code>site_no</code> in <code>site_meta</code> is a primary key — exactly one row per gauge.</p>
<p>A <strong>foreign key</strong> appears in another table to link observations back. <code>site_no</code> in your flow data is a foreign key — it appears thousands of times (once per day per gauge) and connects each observation to its gauge’s metadata.</p>
<p>The join matches on this shared key. Because one gauge has many flow records, this is a <strong>one-to-many</strong> relationship — one <code>site_meta</code> row fans out to match thousands of flow rows.</p>
</div>
</div>
<p><strong>b.</strong> Join <code>site_meta</code> to your flow data using <code>site_no</code> as the key. Use the join type that keeps <strong>all flow records</strong> regardless of whether metadata is available.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>join_data <span class="ot">&lt;-</span> <span class="fu">left_join</span>(raw, site_meta, <span class="at">by =</span> <span class="st">"site_no"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<blockquote class="blockquote">
<p>I chose to use a left join, so that I would keep all my data in the raw dataframe and would only keep the site meta information that matches the raw dataframe. Both dataframes had site numbers in common, so I joined by that parameter.</p>
</blockquote>
<p><strong>c.</strong> Verify the join — this step is not optional:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#verify join </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(join_data) <span class="sc">==</span> <span class="fu">nrow</span>(raw) <span class="co">#row count unchanged </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(join_data<span class="sc">$</span>drain_area_va)) <span class="sc">==</span> <span class="dv">0</span> <span class="co">#no unexpected NAs</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>check_drain_area <span class="ot">&lt;-</span> join_data <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(name <span class="sc">==</span> <span class="st">"Colorado R at Glenwood Springs"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(drain_area_va) <span class="co">#spot check a known value </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Always verify your joins — three checks, every time
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><code>nrow(result) == nrow(left_table)</code> — row count unchanged ✓</li>
<li><code>sum(is.na(new_column)) == 0</code> — no unexpected NAs ✓</li>
<li>Spot-check a known value — numbers are plausible ✓</li>
</ol>
<p>These checks cost 30 seconds and catch errors that would otherwise corrupt every downstream calculation silently. You will join data in every lab this semester. Consider, building this habit now.</p>
</div>
</div>
<hr>
</section>
<section id="graduate-expectations" class="level2">
<h2 class="anchored" data-anchor-id="graduate-expectations">Graduate expectations</h2>
<p>This course is at the graduate level. In addition to producing correct code and outputs, your submission should:</p>
<ul>
<li>Briefly justify methodological choices (e.g., window lengths, alignment for rolling statistics, normalization approaches, and model structure). A short 3–5 sentence justification is sufficient.</li>
<li>Include a simple sensitivity or validation check where appropriate (e.g., compare 7-day vs 14-day rolling windows; use leave-one-year-out cross-validation for the predictive model and report RMSE or MAE).</li>
<li>Report basic uncertainty/robustness: how sensitive are your central conclusions to small changes in preprocessing or parameter choices?</li>
<li>Cite one relevant source (paper, USGS stat documentation, or authoritative report) if you reference an established hydrological statistic (e.g., 7Q10 logic) or external dataset.</li>
</ul>
<hr>
</section>
</section>
<section id="q3" class="level1">
<h1><strong>Question 3</strong>: Per-Unit-Area Normalization</h1>
<p>Lees Ferry’s high discharge reflects its enormous watershed, not necessarily more intense rainfall or runoff. To compare <strong>runoff intensity</strong> across sites with different drainage areas, we normalize by expressing flow per unit area: cfs per square mile.</p>
<p><strong>a.</strong> Add a <code>flow_per_sqmi</code> column to your data.frame.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>runoff_intensity <span class="ot">&lt;-</span> join_data <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">flow_per_sqmi =</span> Flow<span class="sc">/</span>drain_area_va)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>b.</strong> On <code>my.date</code>, build a flextable showing <strong>both raw and normalized rankings</strong> side by side for all 7 gauges. Include columns for gauge name, raw discharge (cfs), drainage area (mi²), normalized flow (cfs/mi²), raw rank, and normalized rank. Sort by raw rank.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>runoff_intensity_mydate <span class="ot">&lt;-</span> runoff_intensity <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Date <span class="sc">==</span> my.date, </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>         name <span class="sc">!=</span> <span class="st">"Colorado R below Hoover Dam"</span>) <span class="sc">%&gt;%</span> <span class="co">#dropping site with NAs in data </span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(name, state, Flow, flow_per_sqmi, drain_area_va)) <span class="sc">%&gt;%</span> </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">raw_rank =</span> <span class="fu">rank</span>(<span class="fu">desc</span>(Flow)), <span class="at">normalized_rank =</span> <span class="fu">rank</span>(<span class="fu">desc</span>(flow_per_sqmi))) <span class="sc">%&gt;%</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(raw_rank)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>runoff_intensity_table <span class="ot">&lt;-</span> <span class="fu">flextable</span>(runoff_intensity_mydate) <span class="sc">%&gt;%</span> </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_header_labels</span>(<span class="at">name =</span> <span class="st">"Gauge Name"</span>, <span class="at">Flow =</span> <span class="st">"Raw Discharge (cfs)"</span>, <span class="at">flow_per_sqmi =</span> <span class="st">"Normalized Flow (cfs/mi²)"</span>, <span class="at">state =</span> <span class="st">"State"</span>, <span class="at">drain_area_va =</span> <span class="st">"Drainage Area (mi²)"</span>, <span class="at">raw_rank =</span> <span class="st">"Raw Ranking"</span>, <span class="at">normalized_rank =</span> <span class="st">"Normalized Ranking"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_caption</span>(<span class="at">caption =</span> <span class="st">"Colorado River Gauges Flow Data on September 30th, 2023, </span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="st">              Ranked by Raw and Normalized Flow"</span>)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>runoff_intensity_table</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-c417a46c{}.cl-c414ca4e{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-c415fb3a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-c415fb44{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-c4160706{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c4160710{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c4160711{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c4160712{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c4160713{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c416071a{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-c417a46c"><thead><tr style="overflow-wrap:break-word;"><th class="cl-c4160706"><p class="cl-c415fb3a"><span class="cl-c414ca4e">Gauge Name</span></p></th><th class="cl-c4160706"><p class="cl-c415fb3a"><span class="cl-c414ca4e">State</span></p></th><th class="cl-c4160710"><p class="cl-c415fb44"><span class="cl-c414ca4e">Raw Discharge (cfs)</span></p></th><th class="cl-c4160710"><p class="cl-c415fb44"><span class="cl-c414ca4e">Normalized Flow (cfs/mi²)</span></p></th><th class="cl-c4160710"><p class="cl-c415fb44"><span class="cl-c414ca4e">Drainage Area (mi²)</span></p></th><th class="cl-c4160710"><p class="cl-c415fb44"><span class="cl-c414ca4e">Raw Ranking</span></p></th><th class="cl-c4160710"><p class="cl-c415fb44"><span class="cl-c414ca4e">Normalized Ranking</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-c4160711"><p class="cl-c415fb3a"><span class="cl-c414ca4e">Little Colorado R near Cameron</span></p></td><td class="cl-c4160711"><p class="cl-c415fb3a"><span class="cl-c414ca4e">AZ</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">6,950</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">0.04908192</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">141,600</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">1</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">5</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c4160711"><p class="cl-c415fb3a"><span class="cl-c414ca4e">Colorado R at Lees Ferry</span></p></td><td class="cl-c4160711"><p class="cl-c415fb3a"><span class="cl-c414ca4e">AZ</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">6,570</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">0.05876565</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">111,800</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">2</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">4</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c4160711"><p class="cl-c415fb3a"><span class="cl-c414ca4e">Colorado R near CO-UT border</span></p></td><td class="cl-c4160711"><p class="cl-c415fb3a"><span class="cl-c414ca4e">CO</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">3,470</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">0.19440865</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">17,849</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">3</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">2</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c4160711"><p class="cl-c415fb3a"><span class="cl-c414ca4e">San Juan R near Bluff</span></p></td><td class="cl-c4160711"><p class="cl-c415fb3a"><span class="cl-c414ca4e">UT</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">680</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">0.02956522</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">23,000</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">4</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">6</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c4160711"><p class="cl-c415fb3a"><span class="cl-c414ca4e">Colorado R at Glenwood Springs</span></p></td><td class="cl-c4160711"><p class="cl-c415fb3a"><span class="cl-c414ca4e">CO</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">533</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">0.36682725</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">1,453</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">5</span></p></td><td class="cl-c4160712"><p class="cl-c415fb44"><span class="cl-c414ca4e">1</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c4160713"><p class="cl-c415fb3a"><span class="cl-c414ca4e">White R near Watson</span></p></td><td class="cl-c4160713"><p class="cl-c415fb3a"><span class="cl-c414ca4e">UT</span></p></td><td class="cl-c416071a"><p class="cl-c415fb44"><span class="cl-c414ca4e">329</span></p></td><td class="cl-c416071a"><p class="cl-c415fb44"><span class="cl-c414ca4e">0.08184080</span></p></td><td class="cl-c416071a"><p class="cl-c415fb44"><span class="cl-c414ca4e">4,020</span></p></td><td class="cl-c416071a"><p class="cl-c415fb44"><span class="cl-c414ca4e">6</span></p></td><td class="cl-c416071a"><p class="cl-c415fb44"><span class="cl-c414ca4e">3</span></p></td></tr></tbody></table></div>
</div>
</div>
<p><strong>c.</strong> Answer in 2–3 sentences: (1) do the raw and normalized rankings differ, and if so, which gauge changes most dramatically? (2) Why does per-area normalization matter for comparing gauges in the Colorado Basin? (3) Name one analysis where you would use raw discharge and one where you would use normalized discharge.</p>
<blockquote class="blockquote">
<p>The raw and normalized rankings do differ. The Colorado River at Glenwood Springs changes the most dramatically, moving from 5th in the raw ranking to 1st in the normalized ranking. Per-area normalization matters for comparing gauges in the Colorado Basin because the drainage basins have dramatically different drainage areas. When comparing flow rates between gauges, it’s important to normalize by the drainage area to more accurately compare flow rates and hydrology of the basins based on their sizes. To analyze the total amount of water flowing through a basin after a storm event, it would be important to use the raw discharge data. However, if one way analyzing the flow rate to track infiltration rates after a storm, it would be important to use the normalized data so the differing sizes of the basins doens’t affect the analysis.</p>
</blockquote>
<hr>
</section>
<section id="q4" class="level1">
<h1><strong>Question 4</strong>: Low-Flow Threshold Monitoring</h1>
<p>Drought managers don’t just watch absolute flow levels — they watch how current conditions compare to <strong>historical norms</strong>. The standard operational metric is the <strong>7Q10</strong>: the lowest 7-day average flow expected to occur once in 10 years. We’ll use a related approach: flag when the 7-day rolling mean falls below the historical 10th percentile.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The USGS computes official low-flow statistics — including the 7Q10 — and makes them accessible via <code>dataRetrieval::readNWISstat()</code>. The thresholds you compute here will closely approximate those official values and follow the same logic water rights lawyers and regulators actually use.</p>
</div>
</div>
<p><strong>a.</strong> For each gauge, compute the <strong>7-day rolling mean</strong> of daily discharge. Use <code>zoo::rollmean()</code> with <code>fill = NA</code> and <code>align = "right"</code> so each value represents the average of the current and 6 preceding days. If you havent see this function before, check out the documentation (<code>?rollmean</code>) and examples to understand how it works.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>low_flow_stats <span class="ot">&lt;-</span> raw <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rolling_mean =</span> <span class="fu">rollmean</span>(Flow, <span class="at">k =</span> <span class="dv">7</span>, <span class="at">align =</span> <span class="st">"right"</span>, <span class="at">fill =</span> <span class="cn">NA</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>b.</strong> Define a <strong>low-flow threshold</strong> for each gauge as the 10th percentile of its historical discharge during <strong>1980–2010</strong>. A flow that is critically low for Lees Ferry might be above average for the Little Colorado — thresholds must be site-specific.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>low_flow_threshold <span class="ot">&lt;-</span> low_flow_stats <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(site_no) <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2010-12-31"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">threshold =</span> <span class="fu">quantile</span>(Flow, <span class="at">probs =</span> <span class="fl">0.1</span>, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span> </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>c.</strong> Add a logical column <code>below_threshold</code> that is <code>TRUE</code> when the 7-day rolling mean is below the gauge’s 10th percentile threshold.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>low_flow_stats_threshold <span class="ot">&lt;-</span> low_flow_threshold <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(low_flow_stats, <span class="at">by =</span> <span class="st">"site_no"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">below_threshold =</span> rolling_mean <span class="sc">&lt;</span> threshold)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>d.</strong> For <strong>Lees Ferry</strong> (site <code>09380000</code>) — the Compact’s primary accounting point — plot the 7-day rolling mean from 2000–2023 using <code>ggplot</code>. Shade periods below threshold in red and add a dashed horizontal reference line at the threshold.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#filter to site and dates</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>lowflow_leesferry <span class="ot">&lt;-</span> low_flow_stats_threshold <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(site_no <span class="sc">==</span> <span class="st">"09380000"</span>, Date <span class="sc">&gt;=</span> (<span class="fu">as.Date</span>(<span class="st">"2000-01-01"</span>)), Date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2023-12-31"</span>)) </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co">#make graph </span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>lowflow_leesferry_plot <span class="ot">&lt;-</span> lowflow_leesferry <span class="sc">%&gt;%</span> </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>Date, <span class="at">y=</span>rolling_mean)) <span class="sc">+</span> </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> <span class="fu">ifelse</span>(below_threshold, threshold, <span class="cn">NA</span>), <span class="at">ymax =</span> <span class="fu">ifelse</span>(below_threshold, rolling_mean, <span class="cn">NA</span>)), <span class="at">fill =</span> <span class="st">"red"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept =</span> threshold),<span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Lees Ferry Flow from 2000-2023"</span>, </span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"7-day rolling mean plotted, with red shaded area considered 'below threshold.'"</span>, </span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Rolling Mean (cfs)"</span>, </span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Data from USGS gauges. Threshold limit set by the 10th percentile of 7-day rolling mean from 1980-2010, represented by the dashed line."</span>) <span class="sc">+</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>lowflow_leesferry_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-01_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>e.</strong> How many days per year, on average, did Lees Ferry fall below its low-flow threshold in <strong>2000–2010</strong> vs.&nbsp;<strong>2011–2023</strong>? Produce a small summary table and answer in 2–3 sentences: (1) did below-threshold days increase or decrease? (2) Is this a shift in isolated dry years or a persistent baseline change? (3) What does this imply for Compact delivery obligations?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>n_distinct(year(Date))</code> counts unique years in a group — useful for computing per-year averages across a multi-year period.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>count_lowflow <span class="ot">&lt;-</span> lowflow_leesferry <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">year</span>(Date) <span class="sc">&gt;=</span> <span class="dv">2000</span> <span class="sc">&amp;</span> <span class="fu">year</span>(Date) <span class="sc">&lt;=</span> <span class="dv">2023</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">period =</span> <span class="fu">if_else</span>(<span class="fu">year</span>(Date) <span class="sc">&lt;=</span> <span class="dv">2010</span>, <span class="st">"2000_2010"</span>, <span class="st">"2011_2023"</span>),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">year =</span> <span class="fu">year</span>(Date)) <span class="sc">%&gt;%</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(period, year) <span class="sc">%&gt;%</span> </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">days_below_threshold =</span> <span class="fu">sum</span>(below_threshold, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(period) <span class="sc">%&gt;%</span> </span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n_years =</span> <span class="fu">n_distinct</span>(year),</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">avg_days_below_threshold =</span> <span class="fu">mean</span>(days_below_threshold))</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>leesferry_summarytable <span class="ot">&lt;-</span> <span class="fu">flextable</span>(count_lowflow) <span class="sc">%&gt;%</span> </span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_header_labels</span>(<span class="at">days_below_threshold =</span> <span class="st">"Total Low-Flow Days"</span>, </span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n_years =</span> <span class="st">"Length of Time Period"</span>, </span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>                    <span class="at">period =</span> <span class="st">"Time Period"</span>, </span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>                    <span class="at">avg_days_below_threshold =</span> <span class="st">"Average Number of Low Flow Days per Year"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_caption</span>(<span class="at">caption =</span> <span class="st">"Lees Ferry Low Flow-Days Averaged per Year from 2000-2023"</span>)</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>leesferry_summarytable</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-c45f3494{}.cl-c45ce87e{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-c45ddb26{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-c45ddb27{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-c45de544{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c45de545{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c45de54e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c45de54f{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c45de550{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c45de551{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-c45f3494"><thead><tr style="overflow-wrap:break-word;"><th class="cl-c45de544"><p class="cl-c45ddb26"><span class="cl-c45ce87e">Time Period</span></p></th><th class="cl-c45de545"><p class="cl-c45ddb27"><span class="cl-c45ce87e">Length of Time Period</span></p></th><th class="cl-c45de545"><p class="cl-c45ddb27"><span class="cl-c45ce87e">Average Number of Low Flow Days per Year</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-c45de54e"><p class="cl-c45ddb26"><span class="cl-c45ce87e">2000_2010</span></p></td><td class="cl-c45de54f"><p class="cl-c45ddb27"><span class="cl-c45ce87e">11</span></p></td><td class="cl-c45de54f"><p class="cl-c45ddb27"><span class="cl-c45ce87e">36.27273</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-c45de550"><p class="cl-c45ddb26"><span class="cl-c45ce87e">2011_2023</span></p></td><td class="cl-c45de551"><p class="cl-c45ddb27"><span class="cl-c45ce87e">13</span></p></td><td class="cl-c45de551"><p class="cl-c45ddb27"><span class="cl-c45ce87e">27.53846</span></p></td></tr></tbody></table></div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(lowflow_leesferry)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<blockquote class="blockquote">
<p>The below-threshold days (on a yearly average) decreased from 2011-2023 (28 average low-flow days compared to 2000-2010 (36 average low-flow days). The 7-day rolling mean plot implies that this change in average low-flow days per year is due to isolated dry years, rather than a basline shift. In regards to Compact delivery problems, the data shows that the flow levels have improved relative to the historical threshold. The low-flow threshold was calculated from 1980-2010, whereas many of the low-flow years are recentl, the threshold should be adjusted to reflect the current state of water availability in a changing climate.</p>
</blockquote>
<hr>
</section>
<section id="q5" class="level1">
<h1><strong>Question 5</strong>: Annual Water Year Summary</h1>
<p>Calendar years are a poor fit for western US hydrology. The <strong>water year</strong> (October 1 – September 30) captures the full snowmelt cycle: snowpack accumulates through winter, melts in spring, and by September the basin has recharged or drawn down for the year. Water year 2023 = October 1, 2022 through September 30, 2023.</p>
<p><strong>a.</strong> Add <code>water_year</code> and <code>month</code> columns to your dataset. The water year is the calendar year of the ending September 30 — months October through December belong to the <em>next</em> water year.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>water_year_df <span class="ot">&lt;-</span> low_flow_stats_threshold  <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">water_year =</span> <span class="fu">ifelse</span>(<span class="fu">month</span>(Date) <span class="sc">&gt;=</span> <span class="dv">10</span>, <span class="fu">year</span>(Date) <span class="sc">+</span> <span class="dv">1</span>, <span class="fu">year</span>(Date)),</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">month =</span> <span class="fu">month</span>(Date))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <code>if_else()</code> to set <code>water_year</code> for Oct–Dec months.</p>
</div>
</div>
<p><strong>b.</strong> For each gauge and water year, compute: total annual discharge, peak daily discharge, and number of days below the low-flow threshold.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>water_year_data <span class="ot">&lt;-</span> water_year_df <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(site_no, water_year, name) <span class="sc">%&gt;%</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">annual_discharge =</span> <span class="fu">sum</span>(Flow),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">peak_daily_discharge =</span> <span class="fu">max</span>(Flow), </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">low_flow_days =</span> <span class="fu">sum</span>(Flow<span class="sc">&lt;</span>threshold))  </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(water_year_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 308 × 6
# Groups:   site_no, water_year [308]
   site_no  water_year name  annual_discharge peak_daily_discharge low_flow_days
   &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;                &lt;dbl&gt;         &lt;int&gt;
 1 09085000       1980 Colo…           432890                 7170             0
 2 09085000       1981 Colo…           271835                 4110           104
 3 09085000       1982 Colo…           469712                 5500             0
 4 09085000       1983 Colo…           603893                11200            14
 5 09085000       1984 Colo…           765741                 9510             0
 6 09085000       1985 Colo…           644976                 9690             0
 7 09085000       1986 Colo…           624342                 7020             0
 8 09085000       1987 Colo…           460126                 5720             0
 9 09085000       1988 Colo…           314527                 4090             5
10 09085000       1989 Colo…           303507                 2920            50
# ℹ 298 more rows</code></pre>
</div>
</div>
<p><strong>c.</strong> Plot <strong>total annual discharge at Lees Ferry</strong> by water year (1980–2023) as a bar chart. Color bars above the long-term median blue and bars below it red. Add a dashed horizontal reference line at the median.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Hint: compute the long-term median and color bars by whether each year’s total is above or below it; add a dashed horizontal line at the median for reference.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>water_year_leesferry <span class="ot">&lt;-</span> water_year_data <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(site_no <span class="sc">==</span> <span class="st">"09380000"</span>, water_year <span class="sc">!=</span> <span class="st">"2024"</span>)<span class="sc">%&gt;%</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">median_discharge =</span> <span class="fu">median</span>(annual_discharge, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">flow_category =</span> <span class="fu">ifelse</span>(annual_discharge <span class="sc">&lt;</span> median_discharge, <span class="st">"Below"</span>, <span class="st">"Above"</span>))</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>lees_ferry_median <span class="ot">&lt;-</span> <span class="fu">median</span>(water_year_leesferry<span class="sc">$</span>annual_discharge, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co">#calculate median annual discharge for lees ferry site</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>water_year_leesferry <span class="ot">&lt;-</span> water_year_leesferry <span class="sc">%&gt;%</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">below =</span> annual_discharge <span class="sc">&lt;</span> lees_ferry_median) <span class="co">#add T/F col</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>wy_leesferry_plot <span class="ot">&lt;-</span> water_year_leesferry <span class="sc">%&gt;%</span> </span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> water_year, <span class="at">y =</span> annual_discharge, <span class="at">fill =</span> below)) <span class="sc">+</span> </span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span> </span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> lees_ferry_median, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> </span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"TRUE"</span> <span class="ot">=</span> <span class="st">"darkred"</span>, <span class="st">"FALSE"</span> <span class="ot">=</span> <span class="st">"dodgerblue4"</span>),</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"TRUE"</span> <span class="ot">=</span> <span class="st">"Below Median"</span>, <span class="st">"FALSE"</span> <span class="ot">=</span> <span class="st">"Above Median"</span>),</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"Flow Status"</span>) <span class="sc">+</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Water Year"</span>, </span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Annual Discharge (cfs)"</span>, </span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Annual Discharge at Lees Ferry Gauge"</span>, </span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="fu">str_wrap</span>(<span class="st">"Dashed line represents median annual discharge."</span>, <span class="at">width =</span> <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>wy_leesferry_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-01_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>In 2–3 sentences: (1) describe the direction and approximate timing of any structural shift in the record, (2) identify one year that stands out as an exception to the dominant pattern and what you know about its cause, and (3) explain what this pattern means for Compact water accounting.</p>
<blockquote class="blockquote">
<p>Starting in 2000, the annual discharge at the Lees Ferry Gauge appears to be consistently decreasing. Before 2000, there were many years that were well-above the long-term median annual discharge, particularly 1983-1987. One exception to the dominant pattern would be 2011, which had an annual discharge well above the long-term median, despite being during a period of consistent low flows. Decreases in spring snowpack and earlier runoff has led to decreases in annual Colorado River Flows at Lees Ferry (Lukas et al., 2020).</p>
</blockquote>
<hr>
</section>
<section id="q6" class="level1">
<h1><strong>Question 6</strong>: Basin-Wide Trend Analysis</h1>
<p>A single gauge tells you about one location. To understand whether drought is consistent across the entire basin — or whether some tributaries are diverging from the main stem — you need to compare all gauges simultaneously on the same scale.</p>
<p>Raw discharge can’t serve this purpose: a large-watershed gauge will always dominate. The solution is a <strong>standardized anomaly</strong> — each year’s flow expressed as standard deviations above or below the site’s own baseline mean:</p>
<p><span class="math display">\[\text{anomaly} = \frac{\bar{Q}_{year} - \bar{Q}_{baseline}}{\sigma_{baseline}}\]</span></p>
<p>where baseline = 1980–2010. An anomaly of –2 means “two standard deviations below normal for this gauge” — directly comparable to the same metric at any other gauge.</p>
<p><strong>a.</strong> Compute the 1980–2010 baseline mean and SD per gauge. Join those stats back to the full annual data and compute the standardized anomaly for every gauge-year combination.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Hint: summarize baseline mean and SD per gauge (1980–2010), join those stats to the annual table, and compute the standardized anomaly as (total_flow − baseline_mean)/baseline_sd. This is a join you’ve seen twice now — verify row counts and NAs after the join.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>baseline_mean_sd <span class="ot">&lt;-</span> water_year_data <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(water_year <span class="sc">&lt;=</span> <span class="st">"2010"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(site_no) <span class="sc">%&gt;%</span> </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">baseline_mean =</span> <span class="fu">mean</span>(annual_discharge, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">baseline_sd =</span> <span class="fu">sd</span>(annual_discharge, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>joined_mean_sd <span class="ot">&lt;-</span> <span class="fu">left_join</span>(water_year_data, baseline_mean_sd, <span class="at">by =</span> <span class="st">"site_no"</span>)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co">#check join worked   </span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(joined_mean_sd) <span class="sc">==</span> <span class="fu">nrow</span>(water_year_data) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>joined_mean_sd_sa <span class="ot">&lt;-</span> joined_mean_sd <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(water_year <span class="sc">!=</span> <span class="dv">2024</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"standardized_anomoly"</span> <span class="ot">=</span> (annual_discharge <span class="sc">-</span> baseline_mean)<span class="sc">/</span>baseline_sd, <span class="at">na.rm =</span> T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>b.</strong> Visualize as a <strong>heatmap</strong>: water year on x, gauge name on y, fill = standardized anomaly. Use a diverging color scale centered at zero (blue = above average, red = below average).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>geom_tile()</code> draws one rectangle per gauge-year. For the color scale, use a diverging color scale centered at zero (e.g., RdBu), clamp extreme values with <code>oob = scales::squish</code>, and wrap long gauge names to keep labels readable.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>heatmap <span class="ot">&lt;-</span> joined_mean_sd_sa <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> water_year, <span class="at">y =</span> name, <span class="at">fill =</span> standardized_anomoly)) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"white"</span>, <span class="at">linewidth =</span> <span class="fl">0.1</span>, <span class="at">na.rm =</span> T) <span class="sc">+</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">palette =</span> <span class="st">"RdBu"</span>, </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">direction =</span> <span class="dv">1</span>, </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">limit =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>), </span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">oob =</span> scales<span class="sc">::</span>squish, </span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"Standardized Anomaly"</span>) <span class="sc">+</span> </span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Water Year"</span>, </span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gauge Name"</span>, </span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Standardized Anomoly of Water Year Discharge by Gauge"</span>,</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Baseline calculated from water years 1980-2010"</span>,</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Data from USGS Gauges, Blue is above average (baseline) values, Red is below average (baseline) values."</span>)</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(heatmap)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-01_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>c.</strong> In 3–4 sentences: (1) describe whether the post-2000 drought signal appears across all gauges or only some, (2) identify two specific years that appear as basin-wide anomalies — one dry, one wet — and name the climate event that caused each, and (3) explain what simultaneous basin-wide anomalies tell you that a single-gauge record cannot.</p>
<blockquote class="blockquote">
<p>Following 2000, the drought signal is relati vely consistent across all gauges. There appears to be a wet anomoly in water year 1984 across all basins. This is likely caused by a record snowpack in the Rocky Mountains, near the headwaters of the Colorado Basin. On the other hand, in water year 2002, there appears to be a dry anomoly across all gauges in the basin (Doesken et al., 1985). 2002 was a historically very dry year and the start of a 20 year-long drought we’ve been seeing since. A single gauge wouldn’t be able to explain that these anomolies are climate-driven. However, if anomolies are occuring on a basin-wide scale, it’s easier to determine climate as tha cause of the basin-wide shift.</p>
</blockquote>
<hr>
</section>
<section id="q7" class="level1">
<h1><strong>Question 7</strong>: The Moving Center of Drought</h1>
<p>You have been asked to understand how the <em>geographic center</em> of streamflow has shifted over time. If drought has disproportionately reduced flow in the southern tributaries, the flow-weighted center of the basin should drift north — proportionally more flow is coming from northern headwater gauges. In exceptional snowmelt years it should shift back.</p>
<p>We measure this with the <strong>flow-weighted mean position</strong>: each gauge’s coordinates are weighted by its fraction of total annual basin flow.</p>
<p><span class="math display">\[\bar{X}_{year} = \frac{\sum (lon_i \times Q_i)}{\sum Q_i} \qquad \bar{Y}_{year} = \frac{\sum (lat_i \times Q_i)}{\sum Q_i}\]</span></p>
<p><strong>a.</strong> Join gauge coordinates (<code>dec_lat_va</code>, <code>dec_long_va</code>) from <code>site_meta</code> to your annual summary. Compute the flow-weighted mean latitude and longitude for each water year.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Hint: join coordinates from <code>site_meta</code> to the annual table, then compute weighted longitude/latitude per year as sum(coord * total_flow) / sum(total_flow). This is your third join — verify row counts, NAs, and spot-check known values.</p>
</div>
</div>
<p>Note: mapping can use <code>map_data("state")</code>; if <code>map_data()</code> is not available install the <code>maps</code> package (<code>install.packages("maps")</code>) or use <code>ggplot2::map_data("state")</code> which provides equivalent polygons.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>fwmc_water_year <span class="ot">&lt;-</span> <span class="fu">left_join</span>(water_year_data, site_meta, <span class="at">by =</span> <span class="st">"site_no"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(water_year) <span class="sc">%&gt;%</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">huc_cd =</span> <span class="cn">NULL</span>, <span class="at">drain_area_va =</span> <span class="cn">NULL</span>, <span class="co">#drop unnecessary columns </span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">weighted_lat =</span> <span class="fu">sum</span>(dec_lat_va <span class="sc">*</span> annual_discharge)<span class="sc">/</span><span class="fu">sum</span>(annual_discharge),</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">weighted_long =</span> <span class="fu">sum</span>(dec_long_va <span class="sc">*</span> annual_discharge)<span class="sc">/</span><span class="fu">sum</span>(annual_discharge)) <span class="sc">%&gt;%</span> </span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>b.</strong> Create a two-panel figure using <code>patchwork</code>:</p>
<ul>
<li><strong>Left</strong>: western US base map with the weighted center plotted as points colored by water year (blue = early, red = recent) and connected by a path through time</li>
<li><strong>Right</strong>: line plot of weighted mean latitude over time with a linear trend line</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Hint: draw a western-US polygon basemap and overlay the annual weighted centers as a colored path and points; beside it, plot weighted latitude over time with a linear trend. Use a diverging color gradient for year progression and <code>patchwork</code> to combine panels.</p>
<p>If you haven’t seen patchwork before, it allows you to combine multiple ggplots into a single figure with simple syntax: <code>plot1 + plot2</code> places them side by side; <code>plot1 / plot2</code> stacks them vertically assuming the package is loaded.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#western-US polygon basemap with annual weighted centers overlayed</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>western_us_map <span class="ot">&lt;-</span> <span class="fu">map_data</span>(<span class="st">"state"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(region <span class="sc">%in%</span> <span class="fu">c</span>( <span class="st">"utah"</span>, <span class="st">"arizona"</span>, <span class="st">"colorado"</span>, <span class="st">"nevada"</span>)) <span class="co">#western US map with states with gauges</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>westernconus_weightedcenter <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_polygon</span>(<span class="at">data =</span> western_us_map, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> long, <span class="at">y =</span> lat, <span class="at">group =</span> group), </span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">fill =</span> <span class="st">"lightgray"</span>, <span class="at">color =</span> <span class="st">"darkgray"</span>, <span class="at">linewidth =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="at">data =</span> fwmc_water_year, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> weighted_long, <span class="at">y =</span> weighted_lat), <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span>  </span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> fwmc_water_year, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> weighted_long, <span class="at">y =</span> weighted_lat, <span class="at">color =</span> water_year), <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_distiller</span>(<span class="at">palette =</span> <span class="st">"RdBu"</span>,  <span class="at">name =</span> <span class="st">"Water Year"</span>) <span class="sc">+</span> </span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Weighted Longitude"</span>, </span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Weighted Latitude"</span>, </span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Western US with Flow-Weighted Centers for Gauges in the Colorado River Basin"</span>, </span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"from 1980 to 2023"</span>, </span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Data from USGS gauges."</span>) <span class="sc">+</span> </span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_map</span>(<span class="at">projection =</span> <span class="st">"mercator"</span>) </span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a><span class="co">#plot weighted latitude over time with a linear trend line </span></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>weightedlat_timeseries <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> fwmc_water_year, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> water_year, <span class="at">y =</span> weighted_lat, <span class="at">color =</span> water_year)) <span class="sc">+</span></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_distiller</span>(<span class="at">palette =</span> <span class="st">"RdBu"</span>, <span class="at">name =</span> <span class="st">"Water Year"</span>) <span class="sc">+</span></span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">0.6</span>) <span class="sc">+</span> </span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Water Year"</span>, </span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Weighted Latitude"</span>, </span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span><span class="st">"Weighted Latitude of Colorado Basin Changes Over Time"</span>,</span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"from 1980 to 2023"</span>, </span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Data from USGS Gauges. Black line shows linear trend."</span>)</span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-32"><a href="#cb37-32" aria-hidden="true" tabindex="-1"></a>westernconus_weightedcenter <span class="sc">+</span> weightedlat_timeseries</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-01_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>c.</strong> Your latitude time series should show two years where the weighted center spikes dramatically northward. Identify those two years and explain: (1) what climate event caused each spike, (2) what they have in common physically, and (3) what the long-term upward trend in weighted latitude suggests about which part of the basin is becoming proportionally more important to total flow — and why that matters for water managers downstream.</p>
<blockquote class="blockquote">
<p>The two years where the flow-weighted center spikes dramatically northward are 1993 and 2023. This relates to particularly wet years in the Upper Colorado River Basin, driven by an above-average snowpack. Therefore, flow is disproportionately increased in the northern latitudes, which pulls the weighted center in that direction. This long-term upwards tresnf in weighted latitude implies that the Upper Basin gauges are contributing more to toatl basin flow. This is imporatnt for water managers downstream because the CRB Compact assumes a relatively consistent distribution of water. Under this assumption, in conjunction with the northern movement of the basin’s hydrologic center, downstream managers face more risks in relation to their water available for use.</p>
</blockquote>
<hr>
</section>
<section id="q8" class="level1">
<h1><strong>Question 8</strong>: Seasonal Regimes and Peak Timing</h1>
<p>Annual totals mask important seasonal structure. The Colorado Basin has two distinct runoff pulses: a <strong>snowmelt</strong> surge in spring (April–June) driven by Rocky Mountain headwater snowpack, and a <strong>monsoon</strong> pulse in late summer (July–September) driven by convective storms across the Arizona-New Mexico plateau. These seasons respond differently to climate forcing — and under warming, the snowmelt season is arriving earlier.</p>
<p><strong>a.</strong> Add a <code>season</code> column using <code>case_when()</code>. Roughly we will define the seasons as follows:</p>
<ul>
<li><strong>Snowmelt</strong>: April–June (months 4–6)</li>
<li><strong>Monsoon</strong>: July–September (months 7–9)</li>
<li><strong>Low-flow</strong>: October–December (months 10–12)</li>
<li><strong>Winter</strong>: January–March (months 1–3)</li>
</ul>
<p>Make <code>season</code> a factor with levels in hydrological order: Snowmelt, Monsoon, Low-flow, Winter.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Hint: extract <code>month</code> from <code>Date</code> with <code>lubridate::month()</code>, create <code>season</code> with <code>case_when()</code> mapping month ranges to labels, then convert to a factor with explicit level ordering:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">|&gt;</span> <span class="fu">mutate</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">month =</span> <span class="fu">month</span>(Date),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">season =</span> <span class="fu">case_when</span>(...),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">season =</span> <span class="fu">factor</span>(season, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'Snowmelt'</span>, <span class="st">'Monsoon'</span>, <span class="st">'Low-flow'</span>, <span class="st">'Winter'</span>))</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>season_data <span class="ot">&lt;-</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(water_year_df, site_meta, <span class="at">by =</span> <span class="st">"site_no"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month =</span> <span class="fu">month</span>(Date),</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">season =</span> <span class="fu">case_when</span>(month <span class="sc">%in%</span> <span class="dv">4</span><span class="sc">:</span><span class="dv">6</span> <span class="sc">~</span> <span class="st">"Snowmelt"</span>, month <span class="sc">%in%</span> <span class="dv">7</span><span class="sc">:</span><span class="dv">9</span> <span class="sc">~</span> <span class="st">"Monsoon"</span>, month <span class="sc">%in%</span> <span class="dv">10</span><span class="sc">:</span><span class="dv">12</span> <span class="sc">~</span> <span class="st">"Low-flow"</span>, month <span class="sc">%in%</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span> <span class="sc">~</span> <span class="st">"Winter"</span>),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">season =</span> <span class="fu">factor</span>(season, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'Snowmelt'</span>, <span class="st">'Monsoon'</span>, <span class="st">'Low-flow'</span>, <span class="st">'Winter'</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>b.</strong> Group by gauge, water year, and season. Summarize total seasonal discharge and normalized runoff per group.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>season_data_sum <span class="ot">&lt;-</span> season_data <span class="sc">%&gt;%</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(site_no, water_year, season) <span class="sc">%&gt;%</span> </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total_seasonal_discharge =</span> <span class="fu">sum</span>(Flow), </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">area_sq_miles =</span> <span class="fu">mean</span>(drain_area_va, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">normalized_runoff =</span> total_seasonal_discharge <span class="sc">/</span> area_sq_miles,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">"drop"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>c.</strong> For each gauge and water year, identify the <strong>date of peak 7-day mean flow</strong> and convert it to day-of-year. Plot peak day-of-year vs.&nbsp;water year for <strong>Lees Ferry</strong> with a linear trend line.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>slice_max(roll7, n = 1, with_ties = FALSE)</code> inside a <code>group_by(site_no, water_year)</code> block selects the single highest 7-day mean row per gauge per year. Then <code>lubridate::yday(Date)</code> converts to day-of-year (1–365).</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>peak_flow_dates <span class="ot">&lt;-</span> season_data <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(site_no, water_year) <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(rolling_mean, <span class="at">n =</span> <span class="dv">1</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">peak_doy =</span> <span class="fu">yday</span>(Date)) <span class="sc">%&gt;%</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>peak_flow_dates_leesferry <span class="ot">&lt;-</span> peak_flow_dates <span class="sc">%&gt;%</span> </span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(site_no <span class="sc">==</span> <span class="st">"09380000"</span>)</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>leesferry_seasonal_peakflow <span class="ot">&lt;-</span> peak_flow_dates_leesferry <span class="sc">%&gt;%</span> </span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> peak_doy, <span class="at">y =</span> water_year)) <span class="sc">+</span> </span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"dodgerblue4"</span>, <span class="at">linewidth =</span> <span class="fl">0.6</span>) <span class="sc">+</span> </span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"7-day Mean Peak Flow"</span>, </span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Water Year"</span>, </span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"7-day Mean Peak Flow for Lees Ferry Gauge on Colorado River"</span>, </span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"from 1980 to 2023"</span>, </span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Data from USGS gauges. Blue line shows linear trend over time."</span>)</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>leesferry_seasonal_peakflow </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-01_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>d.</strong> In 2–3 sentences: (1) describe the direction and magnitude of the peak timing trend, (2) is it statistically visible or buried in noise? (3) What would a two-week earlier peak timing mean operationally for reservoir managers trying to capture spring runoff before it passes downstream?</p>
<blockquote class="blockquote">
<p>The 7-day mean peak timing is trending later in the year, showing a weak upward trend in the graph. However, the wide range of points above and below the trendline imply that this trend is buried in noise. If peak timing was two-weeks earlier, reservoir managers trying to capture spring runoff before it passes downstream would need to free up storage in these reservoirs to capture as much of the peak flow as possible. This would mean earlier releases to adjust for the two-week earlier peak flow date.</p>
</blockquote>
<hr>
</section>
<section id="q9" class="level1">
<h1><strong>Question 9</strong>: Predicting Lees Ferry from Upstream Conditions</h1>
<p>Lees Ferry is the <strong>Compact’s accounting point</strong> — the location where upper basin states must deliver flow to lower basin states. Predicting annual discharge at Lees Ferry from upstream conditions has direct operational value: managers can begin planning deliveries months before the water arrives.</p>
<p>We’ll build a simple but physically grounded model: can Glenwood Springs (an upper Rocky Mountain gauge) predict Lees Ferry annual flow, and, does that relationship change by season?</p>
<section id="data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation">Data Preparation</h2>
<p><strong>a.</strong> Build your model dataset through four sequential operations:</p>
<ol type="1">
<li>Filter <code>annual</code> to Lees Ferry; rename <code>total_flow</code> to <code>lees_flow</code></li>
<li>Join annual Glenwood Springs flow (site <code>09085000</code>); rename to <code>glenwood_flow</code></li>
<li>Join the <strong>dominant season</strong> at Lees Ferry per water year, the season with the highest total discharge</li>
<li>Log-transform both flow variables</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The dominant season: within each water year, which season (Snowmelt, Monsoon, Low-flow, Winter) carried the most flow at Lees Ferry? Filter seasonal summaries to Lees Ferry, then <code>group_by(water_year) |&gt; slice_max(total_flow, n = 1)</code> to select one season per year.</p>
<p>Then join that back to your Lees Ferry &amp; Glenwood annual table by <code>water_year</code>.</p>
<p>This is your fourth join. <strong>Always verify</strong>: the final dataset should have ~44 rows (one per water year, 1980–2023), zero NAs in flow columns, and log-transformed values should be positive.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>leesferry_annual_flow <span class="ot">&lt;-</span> water_year_data <span class="sc">%&gt;%</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(site_no <span class="sc">==</span> <span class="st">"09380000"</span>, water_year <span class="sc">!=</span> <span class="st">"2024"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">lees_flow =</span> annual_discharge) </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>glenwoodsprings_annual_flow <span class="ot">&lt;-</span> water_year_data <span class="sc">%&gt;%</span> </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(site_no <span class="sc">==</span> <span class="st">"09085000"</span>, water_year <span class="sc">!=</span> <span class="st">"2024"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">glenwood_flow =</span> annual_discharge)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>lees_glenwood_annual_flow <span class="ot">&lt;-</span> <span class="fu">left_join</span>(leesferry_annual_flow, glenwoodsprings_annual_flow, <span class="at">by =</span> <span class="st">"water_year"</span>)</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="co">#check join</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(leesferry_annual_flow) <span class="sc">==</span> <span class="fu">nrow</span>(lees_glenwood_annual_flow)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(lees_glenwood_annual_flow<span class="sc">$</span>glenwood_flow)) <span class="sc">==</span> <span class="dv">0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(lees_glenwood_annual_flow<span class="sc">$</span>lees_flow)) <span class="sc">==</span> <span class="dv">0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#dominant season by water year for lees ferry </span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>dominant_season_leesferry <span class="ot">&lt;-</span> season_data_sum<span class="sc">%&gt;%</span> </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(site_no <span class="sc">==</span> <span class="st">"09380000"</span>, water_year <span class="sc">!=</span> <span class="st">"2024"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(water_year) <span class="sc">%&gt;%</span> </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(total_seasonal_discharge, <span class="at">n =</span> <span class="dv">1</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>lees_glenwood_seasonal <span class="ot">&lt;-</span> <span class="fu">left_join</span>(lees_glenwood_annual_flow, dominant_season_leesferry, <span class="at">by =</span> <span class="st">"water_year"</span>)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="co">#check join</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(lees_glenwood_annual_flow) <span class="sc">==</span> <span class="fu">nrow</span>(lees_glenwood_seasonal)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(lees_glenwood_seasonal<span class="sc">$</span>glenwood_flow)) <span class="sc">==</span> <span class="dv">0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(lees_glenwood_seasonal<span class="sc">$</span>lees_flow)) <span class="sc">==</span> <span class="dv">0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#log mutate</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>lees_glenwood_seasonal_log <span class="ot">&lt;-</span> lees_glenwood_seasonal <span class="sc">%&gt;%</span> </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_lees =</span> <span class="fu">log</span>(lees_flow), </span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">log_glenwood =</span> <span class="fu">log</span>(glenwood_flow))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="model-building" class="level2">
<h2 class="anchored" data-anchor-id="model-building">Model Building</h2>
<p><strong>b.</strong> Fit a linear model predicting <code>log_lees</code> from <code>log_glenwood</code>, <code>season</code>, and their interaction, If you haven’t seen linear modeling in R, we will cover it in more detail latter in this course, but, the syntax is straightforward: <code>lm(response ~ predictor1 * predictor2, data = mydata)</code> fits a model with main effects and an interaction term. The interaction (<code>*</code>) allows the relationship between Glenwood and Lees to differ by season while a model without interaction (<code>lm(log_lees ~ log_glenwood + season)</code>) would assume the same Glenwood-Lees relationship in every season.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_lees <span class="sc">~</span> log_glenwood <span class="sc">*</span> season, <span class="at">data =</span> lees_model_data)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>lees_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_lees <span class="sc">~</span> log_glenwood <span class="sc">*</span> season, <span class="at">data =</span> lees_glenwood_seasonal_log)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lees_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_lees ~ log_glenwood * season, data = lees_glenwood_seasonal_log)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.24213 -0.07383 -0.02310  0.03682  0.56592 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  -8.1111     5.2052  -1.558 0.127918    
log_glenwood                  1.7973     0.3912   4.595 5.15e-05 ***
seasonMonsoon                20.1876     5.3373   3.782 0.000566 ***
seasonLow-flow               16.1053     5.9863   2.690 0.010753 *  
seasonWinter                 23.0070     8.3481   2.756 0.009126 ** 
log_glenwood:seasonMonsoon   -1.5456     0.4018  -3.847 0.000470 ***
log_glenwood:seasonLow-flow  -1.2155     0.4545  -2.674 0.011188 *  
log_glenwood:seasonWinter    -1.7699     0.6448  -2.745 0.009385 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1514 on 36 degrees of freedom
Multiple R-squared:  0.713, Adjusted R-squared:  0.6572 
F-statistic: 12.78 on 7 and 36 DF,  p-value: 4.114e-08</code></pre>
</div>
</div>
<p><strong>c.</strong> In 3–4 sentences: (1) report the R² and state whether the overall model is statistically significant, (2) interpret the <code>log_glenwood</code> coefficient as an elasticity — what does it mean physically that the coefficient is greater than 1? (3) describe what the significant negative interaction terms tell you about the upstream-downstream relationship outside of Snowmelt season.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>In a log-log model, the coefficient on <code>log_glenwood</code> is an <strong>elasticity</strong>: a coefficient of 1.8 means a 1% increase in Glenwood Springs flow is associated with a 1.8% increase at Lees Ferry. This super-linear amplification makes physical sense — flow accumulates from tributaries between the two gauges, so an above-average headwater year compounds as it moves downstream.</p>
</div>
</div>
<blockquote class="blockquote">
<p>The R² value is 0.6572, which means the model explains 65.72% of the variance in the Lees Ferry annual flow. The p-value of teh model is 4.11 e-08, which suggests the model is statistically signidicant. An elasticity coefficient of 1.79 means that a 1% increase in flow at Glenwood Springs is associated with a 1.79% increase at Lees Ferry. If the coefficient is greater than 1, this means that there is a larger flow at Lees Ferry than at Glenwood Springs. Therefore, above-average headwater years are amplified as flow accumulates from tributaries downstream. The negative interaction terms for monsoon, low-flow, and winter seasons reduce the baseline elasticity, which implies that the Glenwood Springs flow is not a strong predictor of the flow at Lees Ferry during these seasons.</p>
</blockquote>
<hr>
</section>
</section>
<section id="q10" class="level1">
<h1><strong>Question 10</strong>: Model Evaluation</h1>
<p>A model that fits well on average can still fail in predictable ways. Two core assumptions of linear regression are: predictions should be unbiased across the full range of fitted values, and residuals should be approximately normally distributed. Let’s check both — and look for the outlier year that the model cannot predict.</p>
<p><strong>a.</strong> Use <code>broom::augment()</code> to produce a tidy data frame of predictions and residuals alongside the original data:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(mod, <span class="at">data =</span> lees_model_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Introducing <code>broom</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>broom</code> converts messy R model objects into tidy, pipeable data frames:</p>
<ul>
<li><code>augment(mod)</code> — adds <code>.fitted</code> (predictions) and <code>.resid</code> (residuals) to your data</li>
<li><code>glance(mod)</code> — one-row summary of model fit: R², AIC, p-value</li>
<li><code>tidy(mod)</code> — one-row-per-coefficient table with estimates and p-values</li>
</ul>
<p>Together these make model results as pipeable as any other data frame — straight into <code>ggplot</code> or <code>flextable</code>.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(lees_model, <span class="at">data =</span> lees_glenwood_seasonal_log)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(aug)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 44
Columns: 24
$ site_no.x                &lt;chr&gt; "09380000", "09380000", "09380000", "09380000…
$ water_year               &lt;dbl&gt; 1980, 1981, 1982, 1983, 1984, 1985, 1986, 198…
$ name.x                   &lt;chr&gt; "Colorado R at Lees Ferry", "Colorado R at Le…
$ lees_flow                &lt;dbl&gt; 4462080, 4182140, 4186800, 8819610, 10335100,…
$ peak_daily_discharge.x   &lt;dbl&gt; 34500, 21100, 22200, 92600, 45300, 47400, 524…
$ low_flow_days.x          &lt;int&gt; 30, 90, 76, 18, 0, 3, 9, 6, 68, 80, 84, 90, 1…
$ site_no.y                &lt;chr&gt; "09085000", "09085000", "09085000", "09085000…
$ name.y                   &lt;chr&gt; "Colorado R at Glenwood Springs", "Colorado R…
$ glenwood_flow            &lt;dbl&gt; 432890, 271835, 469712, 603893, 765741, 64497…
$ peak_daily_discharge.y   &lt;dbl&gt; 7170, 4110, 5500, 11200, 9510, 9690, 7020, 57…
$ low_flow_days.y          &lt;int&gt; 0, 104, 0, 14, 0, 0, 0, 0, 5, 50, 148, 45, 85…
$ site_no                  &lt;chr&gt; "09380000", "09380000", "09380000", "09380000…
$ season                   &lt;fct&gt; Monsoon, Low-flow, Monsoon, Monsoon, Snowmelt…
$ total_seasonal_discharge &lt;dbl&gt; 1938400, 1249450, 1175270, 3424100, 3318700, …
$ area_sq_miles            &lt;dbl&gt; 111800, 111800, 111800, 111800, 111800, 11180…
$ normalized_runoff        &lt;dbl&gt; 17.33810, 11.17576, 10.51225, 30.62701, 29.68…
$ log_lees                 &lt;dbl&gt; 15.31113, 15.24633, 15.24745, 15.99249, 16.15…
$ log_glenwood             &lt;dbl&gt; 12.97824, 12.51295, 13.05988, 13.31115, 13.54…
$ .fitted                  &lt;dbl&gt; 15.34278, 15.27409, 15.36333, 15.42657, 16.24…
$ .resid                   &lt;dbl&gt; -0.031655369, -0.027760740, -0.115879672, 0.5…
$ .hat                     &lt;dbl&gt; 0.03997428, 0.30256615, 0.04886508, 0.1068733…
$ .sigma                   &lt;dbl&gt; 0.1534943, 0.1534886, 0.1522726, 0.1155201, 0…
$ .cooksd                  &lt;dbl&gt; 2.368756e-04, 2.612686e-03, 3.953117e-03, 2.3…
$ .std.resid               &lt;dbl&gt; -0.21333216, -0.21949767, -0.78457880, 3.9541…</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(lees_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic      p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.713         0.657 0.151      12.8 0.0000000411     7   25.0 -32.1 -16.0
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p><strong>b.</strong> Create a <strong>predicted vs.&nbsp;actual scatter plot</strong>. Add a dashed 1:1 reference line (perfect prediction). Color points by <code>season</code>. Identify any point that sits noticeably off the line.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>geom_abline(slope = 1, intercept = 0, linetype = "dashed")</code> draws the 1:1 line. Points above it = underpredicted (actual &gt; predicted); points below = overpredicted.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>actual_predicted_plot <span class="ot">&lt;-</span> aug <span class="sc">%&gt;%</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>.fitted, <span class="at">y =</span> log_lees, <span class="at">color =</span> season)) <span class="sc">+</span> </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Predicted Flow (log cfs)"</span>,</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Actual Flow (log cfs)"</span>, </span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Season"</span>,</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Actual vs. Predicted Flow at Lees Ferry"</span>, </span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"from water years 1980 to 2023."</span>, </span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Data from USGS gauges. Linear model built to predict flow at Lees Ferry. Points above the dashed line are underpredicted, points below the dashed line are overpredicted."</span>) <span class="sc">+</span> </span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> <span class="fu">filter</span>(aug, <span class="fu">abs</span>(.resid) <span class="sc">&gt;</span> <span class="fl">0.15</span>), <span class="fu">aes</span>(<span class="at">label =</span> water_year), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">nudge_y =</span> <span class="fl">0.05</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a>actual_predicted_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-01_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>c.</strong> Plot a <strong>histogram of the residuals</strong> with a vertical dashed line at zero.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>residual_plot <span class="ot">&lt;-</span> aug <span class="sc">%&gt;%</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> .resid)) <span class="sc">+</span> </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"dodgerblue4"</span>) <span class="sc">+</span> </span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Residuals"</span>, </span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>, </span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Residuals of Lees Ferry Flow Model"</span>, </span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"from water years 1980 to 2023"</span>, </span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Data from USGS gauges. Residuals from linear model predicting flow at Lees Ferry Site on Colorado River."</span>)</span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a>residual_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-01_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>d.</strong> In 3–4 sentences: (1) identify the outlier water year visible in your scatter plot. Which year is it and why did the model fail to predict it? (2) Do the residuals appear approximately normal, or is there a tail that concerns you? (3) Name two additional predictors that would most improve this model and explain the physical mechanism behind each.</p>
<blockquote class="blockquote">
<p>The outlier water year visible in the scatter plot is 1983. The model significanyl underpredicted this year because it was a particularly wet year, with high flow levels that were not commonly seen in the data used to build the model. The residuals appear to be mostly centered around zero, but there is a right tail that is concerning. This implies that the model struggles with predicting flows during really wet years. To improve this model, adding spring snowpack upstream as a predictor would help better predict on above-average wet years. Also, adding an infiltration rate predictor would help train the model on flows compared soil conditions.</p>
</blockquote>
<hr>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Doesken, Nolan J, Thomas B McKee, and Department of Atmospheric Science Colorado Climate Center. Colorado Climate Summary Water-Year Series: October 1983-September 1984. Colorado State University. Libraries, 1985. Print.</p>
<p>Lukas, Jeff et al.&nbsp;Colorado River Basin Climate and Hydrology: State of the Science. Boulder, Colo: Western Water Assessment, University of Colorado Boulder, Cooperative Institute for Research in Environmental Sciences, 2020. Web.</p>
<hr>
</section>
<section id="going-further-ungraded" class="level1">
<h1>Going Further (ungraded)</h1>
<p>The model in Q9 predicts Lees Ferry from a single upstream gauge. <code>dataRetrieval</code> gives you access to hundreds more across the basin. Could a multi-gauge ensemble prediction outperform the single-gauge model? Could peak flows in March predict the following June’s flow at Lees Ferry months before snowmelt begins?</p>
<p>These are real operational forecasting questions that USBR and state water agencies work on every year. The data is already in your hands to try!</p>
<hr>
</section>
<section id="summary" class="level1">
<h1>Summary</h1>
<p>In this lab you built a complete analytical pipeline for one of the most consequential river systems in North America:</p>
<ul>
<li><strong>Retrieved</strong> 44 years of daily streamflow directly from the USGS NWIS API using <code>dataRetrieval</code></li>
<li><strong>Joined</strong> gauge metadata using relational keys — and verified every join</li>
<li><strong>Normalized</strong> by drainage area to enable fair comparisons across the basin</li>
<li><strong>Detected</strong> low-flow threshold exceedances using rolling statistics for operational drought monitoring</li>
<li><strong>Aggregated</strong> by water year and season — the natural temporal units of western hydrology</li>
<li><strong>Visualized</strong> basin-wide trends with a standardized anomaly heatmap and a flow-weighted spatial center analysis</li>
<li><strong>Modeled</strong> the upstream-downstream relationship at the Compact’s accounting point</li>
<li><strong>Evaluated</strong> model assumptions and identified the outlier year the model couldn’t predict</li>
</ul>
<p>Every tool — <code>dplyr</code>, <code>ggplot2</code>, <code>zoo</code>, <code>patchwork</code>, <code>broom</code>, <code>flextable</code> — recurs in work you will inevitabbly do. The key is that the workflow is always the same: get → tidy → explore → model → communicate.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>